using System;
public class b
{
    public int? b2 { get; set; }
    public int? b3 { get; set; }
    public int? b4 { get; set; }
    public int? b5 { get; set; }
    public int? b6 { get; set; }
    public int? b7 { get; set; }
    public int? b8 { get; set; }
    public int? b9 { get; set; }
    public int? b10 { get; set; }
    public int? b11 { get; set; }
    public int? b12 { get; set; }
    public int? b13 { get; set; }
    public int? b14 { get; set; }
    public int? b15 { get; set; }
    public int? b16 { get; set; }
    public int? b17 { get; set; }
    public int? b18 { get; set; }
    public int? b19 { get; set; }
    public int? b20 { get; set; }
    public int? b21 { get; set; }
    public int? b22 { get; set; }
    public int? b23 { get; set; }
    public int? b24 { get; set; }
    public int? b25 { get; set; }
    public int? b26 { get; set; }
    public int? b27 { get; set; }
    public int? b28 { get; set; }
    public int? b29 { get; set; }
    public int? b30 { get; set; }
    public int? b31 { get; set; }
    public int? b32 { get; set; }
    public int? b33 { get; set; }
    public int? b34 { get; set; }
    public int? b35 { get; set; }
    public int? b36 { get; set; }
    public int? b37 { get; set; }
    public int? b38 { get; set; }
    public int? b39 { get; set; }
    public int? b40 { get; set; }
    public int? b41 { get; set; }
    public int? b42 { get; set; }
    public int? b43 { get; set; }
    public int? b44 { get; set; }
    public int? b45 { get; set; }
    public int? b46 { get; set; }
    public int? b47 { get; set; }
    public int? b48 { get; set; }
    public int? b49 { get; set; }
    public int? b50 { get; set; }
    public int? b51 { get; set; }
    public int? b52 { get; set; }
    public int? b53 { get; set; }
    public int? b54 { get; set; }
    public int? b55 { get; set; }
    public int? b56 { get; set; }
    public int? b57 { get; set; }
    public int? b58 { get; set; }
    public int? b59 { get; set; }
    public int? b60 { get; set; }
    public int? b61 { get; set; }
    public int? b62 { get; set; }
    public int? b63 { get; set; }
    public int? b64 { get; set; }
    public int? b65 { get; set; }
    public int? b66 { get; set; }
    public int? b67 { get; set; }
    public int? b68 { get; set; }
    public int? b69 { get; set; }
    public int? b70 { get; set; }
    public int? b71 { get; set; }
    public int? b72 { get; set; }
    public int? b73 { get; set; }
    public int? b74 { get; set; }
    public int? b75 { get; set; }
    public int? b76 { get; set; }
    public int? b77 { get; set; }
    public int? b78 { get; set; }
    public int? b79 { get; set; }
    public int? b80 { get; set; }
    public int? b81 { get; set; }
    public int? b82 { get; set; }
    public int? b83 { get; set; }
    public int? b84 { get; set; }
    public int? b85 { get; set; }
    public int? b86 { get; set; }
    public int? b87 { get; set; }
    public int? b88 { get; set; }
    public int? b89 { get; set; }
    public int? b90 { get; set; }
    public int? b91 { get; set; }
    public int? b92 { get; set; }
    public int? b93 { get; set; }
    public int? b94 { get; set; }
    public int? b95 { get; set; }
    public int? b96 { get; set; }
    public int? b97 { get; set; }
    public int? b98 { get; set; }
    public int? b99 { get; set; }
    public int? b100 { get; set; }
    public int? b101 { get; set; }
    public int? b102 { get; set; }
    public int? b103 { get; set; }
    public int? b104 { get; set; }
    public int? b105 { get; set; }
    public int? b106 { get; set; }
    public int? b107 { get; set; }
    public int? b108 { get; set; }
    public int? b109 { get; set; }
    public int? b110 { get; set; }
    public int? b111 { get; set; }
    public int? b112 { get; set; }
    public int? b113 { get; set; }
    public int? b114 { get; set; }
    public int? b115 { get; set; }
    public int? b116 { get; set; }
    public int? b117 { get; set; }
    public int? b118 { get; set; }
    public int? b119 { get; set; }
    public int? b120 { get; set; }
    public int? b121 { get; set; }
    public int? b122 { get; set; }
    public int? b123 { get; set; }
    public int? b124 { get; set; }
    public int? b125 { get; set; }
    public int? b126 { get; set; }
    public int? b127 { get; set; }
    public int? b128 { get; set; }
    public int? b129 { get; set; }
    public int? b130 { get; set; }
    public int? b131 { get; set; }
    public int? b132 { get; set; }
    public int? b133 { get; set; }
    public int? b134 { get; set; }
    public int? b135 { get; set; }
    public int? b136 { get; set; }
    public int? b137 { get; set; }
    public int? b138 { get; set; }
    public int? b139 { get; set; }
    public int? b140 { get; set; }
    public int? b141 { get; set; }
    public int? b142 { get; set; }
    public int? b143 { get; set; }
    public int? b144 { get; set; }
    public int? b145 { get; set; }
    public int? b146 { get; set; }
    public int? b147 { get; set; }
    public int? b148 { get; set; }
    public int? b149 { get; set; }
    public int? b150 { get; set; }
    public int? b151 { get; set; }
    public int? b152 { get; set; }
    public int? b153 { get; set; }
    public int? b154 { get; set; }
    public int? b155 { get; set; }
    public int? b156 { get; set; }
    public int? b157 { get; set; }
    public int? b158 { get; set; }
    public int? b159 { get; set; }
    public int? b160 { get; set; }
    public int? b161 { get; set; }
    public int? b162 { get; set; }
    public int? b163 { get; set; }
    public int? b164 { get; set; }
    public int? b165 { get; set; }
    public int? b166 { get; set; }
    public int? b167 { get; set; }
    public int? b168 { get; set; }
    public int? b169 { get; set; }
    public int? b170 { get; set; }
    public int? b171 { get; set; }
    public int? b172 { get; set; }
    public int? b173 { get; set; }
    public int? b174 { get; set; }
    public int? b175 { get; set; }
    public int? b176 { get; set; }
    public int? b177 { get; set; }
    public int? b178 { get; set; }
    public int? b179 { get; set; }
    public int? b180 { get; set; }
    public int? b181 { get; set; }
    public int? b182 { get; set; }
    public int? b183 { get; set; }
    public int? b184 { get; set; }
    public int? b185 { get; set; }
    public int? b186 { get; set; }
    public int? b187 { get; set; }
    public int? b188 { get; set; }
    public int? b189 { get; set; }
    public int? b190 { get; set; }
    public int? b191 { get; set; }
    public int? b192 { get; set; }
    public int? b193 { get; set; }
    public int? b194 { get; set; }
    public int? b195 { get; set; }
    public int? b196 { get; set; }
    public int? b197 { get; set; }
    public int? b198 { get; set; }
    public int? b199 { get; set; }
    public int? b200 { get; set; }
    public int? b201 { get; set; }
    public int? b202 { get; set; }
    public int? b203 { get; set; }
    public int? b204 { get; set; }
    public int? b205 { get; set; }
    public int? b206 { get; set; }
    public int? b207 { get; set; }
    public int? b208 { get; set; }
    public int? b209 { get; set; }
    public int? b210 { get; set; }
    public int? b211 { get; set; }
    public int? b212 { get; set; }
    public int? b213 { get; set; }
    public int? b214 { get; set; }
    public int? b215 { get; set; }
    public int? b216 { get; set; }
    public int? b217 { get; set; }
    public int? b218 { get; set; }
    public int? b219 { get; set; }
    public int? b220 { get; set; }
    public int? b221 { get; set; }
    public int? b222 { get; set; }
    public int? b223 { get; set; }
    public int? b224 { get; set; }
    public int? b225 { get; set; }
    public int? b226 { get; set; }
    public int? b227 { get; set; }
    public int? b228 { get; set; }
    public int? b229 { get; set; }
    public int? b230 { get; set; }
    public int? b231 { get; set; }
    public int? b232 { get; set; }
    public int? b233 { get; set; }
    public int? b234 { get; set; }
    public int? b235 { get; set; }
    public int? b236 { get; set; }
    public int? b237 { get; set; }
    public int? b238 { get; set; }
    public int? b239 { get; set; }
    public int? b240 { get; set; }
    public int? b241 { get; set; }
    public int? b242 { get; set; }
    public int? b243 { get; set; }
    public int? b244 { get; set; }
    public int? b245 { get; set; }
    public int? b246 { get; set; }
    public int? b247 { get; set; }
    public int? b248 { get; set; }
    public int? b249 { get; set; }
    public int? b250 { get; set; }
    public int? b251 { get; set; }
    public int? b252 { get; set; }
    public int? b253 { get; set; }
    public int? b254 { get; set; }
    public int? b255 { get; set; }
    public int? b256 { get; set; }
    public int? b257 { get; set; }
    public int? b258 { get; set; }
    public int? b259 { get; set; }
    public int? b260 { get; set; }
    public int? b261 { get; set; }
    public int? b262 { get; set; }
    public int? b263 { get; set; }
    public int? b264 { get; set; }
    public int? b265 { get; set; }
    public int? b266 { get; set; }
    public int? b267 { get; set; }
    public int? b268 { get; set; }
    public int? b269 { get; set; }
    public int? b270 { get; set; }
    public int? b271 { get; set; }
    public int? b272 { get; set; }
    public int? b273 { get; set; }
    public int? b274 { get; set; }
    public int? b275 { get; set; }
    public int? b276 { get; set; }
    public int? b277 { get; set; }
    public int? b278 { get; set; }
    public int? b279 { get; set; }
    public int? b280 { get; set; }
    public int? b281 { get; set; }
    public int? b282 { get; set; }
    public int? b283 { get; set; }
    public int? b284 { get; set; }
    public int? b285 { get; set; }
    public int? b286 { get; set; }
    public int? b287 { get; set; }
    public int? b288 { get; set; }
    public int? b289 { get; set; }
    public int? b290 { get; set; }
    public int? b291 { get; set; }
    public int? b292 { get; set; }
    public int? b293 { get; set; }
    public int? b294 { get; set; }
    public int? b295 { get; set; }
    public int? b296 { get; set; }
    public int? b297 { get; set; }
    public int? b298 { get; set; }
    public int? b299 { get; set; }
    public int? b300 { get; set; }
    public int? b301 { get; set; }
    public int? b302 { get; set; }
    public int? b303 { get; set; }
    public int? b304 { get; set; }
    public int? b305 { get; set; }
    public int? b306 { get; set; }
    public int? b307 { get; set; }
    public int? b308 { get; set; }
    public int? b309 { get; set; }
    public int? b310 { get; set; }
    public int? b311 { get; set; }
    public int? b312 { get; set; }
    public int? b313 { get; set; }
    public int? b314 { get; set; }
    public int? b315 { get; set; }
    public int? b316 { get; set; }
    public int? b317 { get; set; }
    public int? b318 { get; set; }
    public int? b319 { get; set; }
    public int? b320 { get; set; }
    public int? b321 { get; set; }
    public int? b322 { get; set; }
    public int? b323 { get; set; }
    public int? b324 { get; set; }
    public int? b325 { get; set; }
    public int? b326 { get; set; }
    public int? b327 { get; set; }
    public int? b328 { get; set; }
    public int? b329 { get; set; }
    public int? b330 { get; set; }
    public int? b331 { get; set; }
    public int? b332 { get; set; }
    public int? b333 { get; set; }
    public int? b334 { get; set; }
    public int? b335 { get; set; }
    public int? b336 { get; set; }
    public int? b337 { get; set; }
    public int? b338 { get; set; }
    public int? b339 { get; set; }
    public int? b340 { get; set; }
    public int? b341 { get; set; }
    public int? b342 { get; set; }
    public int? b343 { get; set; }
    public int? b344 { get; set; }
    public int? b345 { get; set; }
    public int? b346 { get; set; }
    public int? b347 { get; set; }
    public int? b348 { get; set; }
    public int? b349 { get; set; }
    public int? b350 { get; set; }
    public int? b351 { get; set; }
    public int? b352 { get; set; }
    public int? b353 { get; set; }
    public int? b354 { get; set; }
    public int? b355 { get; set; }
    public int? b356 { get; set; }
    public int? b357 { get; set; }
    public int? b358 { get; set; }
    public int? b359 { get; set; }
    public int? b360 { get; set; }
    public int? b361 { get; set; }
    public int? b362 { get; set; }
    public int? b363 { get; set; }
    public int? b364 { get; set; }
    public int? b365 { get; set; }
    public int? b366 { get; set; }
    public int? b367 { get; set; }
    public int? b368 { get; set; }
    public int? b369 { get; set; }
    public int? b370 { get; set; }
    public int? b371 { get; set; }
    public int? b372 { get; set; }
    public int? b373 { get; set; }
    public int? b374 { get; set; }
    public int? b375 { get; set; }
    public int? b376 { get; set; }
    public int? b377 { get; set; }
    public int? b378 { get; set; }
    public int? b379 { get; set; }
    public int? b380 { get; set; }
    public int? b381 { get; set; }
    public int? b382 { get; set; }
    public int? b383 { get; set; }
    public int? b384 { get; set; }
    public int? b385 { get; set; }
    public int? b386 { get; set; }
    public int? b387 { get; set; }
    public int? b388 { get; set; }
    public int? b389 { get; set; }
    public int? b390 { get; set; }
    public int? b391 { get; set; }
    public int? b392 { get; set; }
    public int? b393 { get; set; }
    public int? b394 { get; set; }
    public int? b395 { get; set; }
    public int? b396 { get; set; }
    public int? b397 { get; set; }
    public int? b398 { get; set; }
    public int? b399 { get; set; }
    public int? b400 { get; set; }
    public int? b401 { get; set; }
    public int? b402 { get; set; }
    public int? b403 { get; set; }
    public int? b404 { get; set; }
    public int? b405 { get; set; }
    public int? b406 { get; set; }
    public int? b407 { get; set; }
    public int? b408 { get; set; }
    public int? b409 { get; set; }
    public int? b410 { get; set; }
    public int? b411 { get; set; }
    public int? b412 { get; set; }
    public int? b413 { get; set; }
    public int? b414 { get; set; }
    public int? b415 { get; set; }
    public int? b416 { get; set; }
    public int? b417 { get; set; }
    public int? b418 { get; set; }
    public int? b419 { get; set; }
    public int? b420 { get; set; }
    public int? b421 { get; set; }
    public int? b422 { get; set; }
    public int? b423 { get; set; }
    public int? b424 { get; set; }
    public int? b425 { get; set; }
    public int? b426 { get; set; }
    public int? b427 { get; set; }
    public int? b428 { get; set; }
    public int? b429 { get; set; }
    public int? b430 { get; set; }
    public int? b431 { get; set; }
    public int? b432 { get; set; }
    public int? b433 { get; set; }
    public int? b434 { get; set; }
    public int? b435 { get; set; }
    public int? b436 { get; set; }
    public int? b437 { get; set; }
    public int? b438 { get; set; }
    public int? b439 { get; set; }
    public int? b440 { get; set; }
    public int? b441 { get; set; }
    public int? b442 { get; set; }
    public int? b443 { get; set; }
    public int? b444 { get; set; }
    public int? b445 { get; set; }
    public int? b446 { get; set; }
    public int? b447 { get; set; }
    public int? b448 { get; set; }
    public int? b449 { get; set; }
    public int? b450 { get; set; }
    public int? b451 { get; set; }
    public int? b452 { get; set; }
    public int? b453 { get; set; }
    public int? b454 { get; set; }
    public int? b455 { get; set; }
    public int? b456 { get; set; }
    public int? b457 { get; set; }
    public int? b458 { get; set; }
    public int? b459 { get; set; }
    public int? b460 { get; set; }
    public int? b461 { get; set; }
    public int? b462 { get; set; }
    public int? b463 { get; set; }
    public int? b464 { get; set; }
    public int? b465 { get; set; }
    public int? b466 { get; set; }
    public int? b467 { get; set; }
    public int? b468 { get; set; }
    public int? b469 { get; set; }
    public int? b470 { get; set; }
    public int? b471 { get; set; }
    public int? b472 { get; set; }
    public int? b473 { get; set; }
    public int? b474 { get; set; }
    public int? b475 { get; set; }
    public int? b476 { get; set; }
    public int? b477 { get; set; }
    public int? b478 { get; set; }
    public int? b479 { get; set; }
    public int? b480 { get; set; }
    public int? b481 { get; set; }
    public int? b482 { get; set; }
    public int? b483 { get; set; }
    public int? b484 { get; set; }
    public int? b485 { get; set; }
    public int? b486 { get; set; }
    public int? b487 { get; set; }
    public int? b488 { get; set; }
    public int? b489 { get; set; }
    public int? b490 { get; set; }
    public int? b491 { get; set; }
    public int? b492 { get; set; }
    public int? b493 { get; set; }
    public int? b494 { get; set; }
    public int? b495 { get; set; }
    public int? b496 { get; set; }
    public int? b497 { get; set; }
    public int? b498 { get; set; }
    public int? b499 { get; set; }
    public int? b500 { get; set; }
    public int? b501 { get; set; }
    public int? b502 { get; set; }
    public int? b503 { get; set; }
    public int? b504 { get; set; }
    public int? b505 { get; set; }
    public int? b506 { get; set; }
    public int? b507 { get; set; }
    public int? b508 { get; set; }
    public int? b509 { get; set; }
    public int? b510 { get; set; }
    public int? b511 { get; set; }
    public int? b512 { get; set; }
    public int? b513 { get; set; }
    public int? b514 { get; set; }
    public int? b515 { get; set; }
    public int? b516 { get; set; }
    public int? b517 { get; set; }
    public int? b518 { get; set; }
    public int? b519 { get; set; }
    public int? b520 { get; set; }
    public int? b521 { get; set; }
    public int? b522 { get; set; }
    public int? b523 { get; set; }
    public int? b524 { get; set; }
    public int? b525 { get; set; }
    public int? b526 { get; set; }
    public int? b527 { get; set; }
    public int? b528 { get; set; }
    public int? b529 { get; set; }
    public int? b530 { get; set; }
    public int? b531 { get; set; }
    public int? b532 { get; set; }
    public int? b533 { get; set; }
    public int? b534 { get; set; }
    public int? b535 { get; set; }
    public int? b536 { get; set; }
    public int? b537 { get; set; }
    public int? b538 { get; set; }
    public int? b539 { get; set; }
    public int? b540 { get; set; }
    public int? b541 { get; set; }
    public int? b542 { get; set; }
    public int? b543 { get; set; }
    public int? b544 { get; set; }
    public int? b545 { get; set; }
    public int? b546 { get; set; }
    public int? b547 { get; set; }
    public int? b548 { get; set; }
    public int? b549 { get; set; }
    public int? b550 { get; set; }
    public int? b551 { get; set; }
    public int? b552 { get; set; }
    public int? b553 { get; set; }
    public int? b554 { get; set; }
    public int? b555 { get; set; }
    public int? b556 { get; set; }
    public int? b557 { get; set; }
    public int? b558 { get; set; }
    public int? b559 { get; set; }
    public int? b560 { get; set; }
    public int? b561 { get; set; }
    public int? b562 { get; set; }
    public int? b563 { get; set; }
    public int? b564 { get; set; }
    public int? b565 { get; set; }
    public int? b566 { get; set; }
    public int? b567 { get; set; }
    public int? b568 { get; set; }
    public int? b569 { get; set; }
    public int? b570 { get; set; }
    public int? b571 { get; set; }
    public int? b572 { get; set; }
    public int? b573 { get; set; }
    public int? b574 { get; set; }
    public int? b575 { get; set; }
    public int? b576 { get; set; }
    public int? b577 { get; set; }
    public int? b578 { get; set; }
    public int? b579 { get; set; }
    public int? b580 { get; set; }
    public int? b581 { get; set; }
    public int? b582 { get; set; }
    public int? b583 { get; set; }
    public int? b584 { get; set; }
    public int? b585 { get; set; }
    public int? b586 { get; set; }
    public int? b587 { get; set; }
    public int? b588 { get; set; }
    public int? b589 { get; set; }
    public int? b590 { get; set; }
    public int? b591 { get; set; }
    public int? b592 { get; set; }
    public int? b593 { get; set; }
    public int? b594 { get; set; }
    public int? b595 { get; set; }
    public int? b596 { get; set; }
    public int? b597 { get; set; }
    public int? b598 { get; set; }
    public int? b599 { get; set; }
    public int? b600 { get; set; }
    public int? b601 { get; set; }
    public int? b602 { get; set; }
    public int? b603 { get; set; }
    public int? b604 { get; set; }
    public int? b605 { get; set; }
    public int? b606 { get; set; }
    public int? b607 { get; set; }
    public int? b608 { get; set; }
    public int? b609 { get; set; }
    public int? b610 { get; set; }
    public int? b611 { get; set; }
    public int? b612 { get; set; }
    public int? b613 { get; set; }
    public int? b614 { get; set; }
    public int? b615 { get; set; }
    public int? b616 { get; set; }
    public int? b617 { get; set; }
    public int? b618 { get; set; }
    public int? b619 { get; set; }
    public int? b620 { get; set; }
    public int? b621 { get; set; }
    public int? b622 { get; set; }
    public int? b623 { get; set; }
    public int? b624 { get; set; }
    public int? b625 { get; set; }
    public int? b626 { get; set; }
    public int? b627 { get; set; }
    public int? b628 { get; set; }
    public int? b629 { get; set; }
    public int? b630 { get; set; }
    public int? b631 { get; set; }
    public int? b632 { get; set; }
    public int? b633 { get; set; }
    public int? b634 { get; set; }
    public int? b635 { get; set; }
    public int? b636 { get; set; }
    public int? b637 { get; set; }
    public int? b638 { get; set; }
    public int? b639 { get; set; }
    public int? b640 { get; set; }
    public int? b641 { get; set; }
    public int? b642 { get; set; }
    public int? b643 { get; set; }
    public int? b644 { get; set; }
    public int? b645 { get; set; }
    public int? b646 { get; set; }
    public int? b647 { get; set; }
    public int? b648 { get; set; }
    public int? b649 { get; set; }
    public int? b650 { get; set; }
    public int? b651 { get; set; }
    public int? b652 { get; set; }
    public int? b653 { get; set; }
    public int? b654 { get; set; }
    public int? b655 { get; set; }
    public int? b656 { get; set; }
    public int? b657 { get; set; }
    public int? b658 { get; set; }
    public int? b659 { get; set; }
    public int? b660 { get; set; }
    public int? b661 { get; set; }
    public int? b662 { get; set; }
    public int? b663 { get; set; }
    public int? b664 { get; set; }
    public int? b665 { get; set; }
    public int? b666 { get; set; }
    public int? b667 { get; set; }
    public int? b668 { get; set; }
    public int? b669 { get; set; }
    public int? b670 { get; set; }
    public int? b671 { get; set; }
    public int? b672 { get; set; }
    public int? b673 { get; set; }
    public int? b674 { get; set; }
    public int? b675 { get; set; }
    public int? b676 { get; set; }
    public int? b677 { get; set; }
    public int? b678 { get; set; }
    public int? b679 { get; set; }
    public int? b680 { get; set; }
    public int? b681 { get; set; }
    public int? b682 { get; set; }
    public int? b683 { get; set; }
    public int? b684 { get; set; }
    public int? b685 { get; set; }
    public int? b686 { get; set; }
    public int? b687 { get; set; }
    public int? b688 { get; set; }
    public int? b689 { get; set; }
    public int? b690 { get; set; }
    public int? b691 { get; set; }
    public int? b692 { get; set; }
    public int? b693 { get; set; }
    public int? b694 { get; set; }
    public int? b695 { get; set; }
    public int? b696 { get; set; }
    public int? b697 { get; set; }
    public int? b698 { get; set; }
    public int? b699 { get; set; }
    public int? b700 { get; set; }
    public int? b701 { get; set; }
    public int? b702 { get; set; }
    public int? b703 { get; set; }
    public int? b704 { get; set; }
    public int? b705 { get; set; }
    public int? b706 { get; set; }
    public int? b707 { get; set; }
    public int? b708 { get; set; }
    public int? b709 { get; set; }
    public int? b710 { get; set; }
    public int? b711 { get; set; }
    public int? b712 { get; set; }
    public int? b713 { get; set; }
    public int? b714 { get; set; }
    public int? b715 { get; set; }
    public int? b716 { get; set; }
    public int? b717 { get; set; }
    public int? b718 { get; set; }
    public int? b719 { get; set; }
    public int? b720 { get; set; }
    public int? b721 { get; set; }
    public int? b722 { get; set; }
    public int? b723 { get; set; }
    public int? b724 { get; set; }
    public int? b725 { get; set; }
    public int? b726 { get; set; }
    public int? b727 { get; set; }
    public int? b728 { get; set; }
    public int? b729 { get; set; }
    public int? b730 { get; set; }
    public int? b731 { get; set; }
    public int? b732 { get; set; }
    public int? b733 { get; set; }
    public int? b734 { get; set; }
    public int? b735 { get; set; }
    public int? b736 { get; set; }
    public int? b737 { get; set; }
    public int? b738 { get; set; }
    public int? b739 { get; set; }
    public int? b740 { get; set; }
    public int? b741 { get; set; }
    public int? b742 { get; set; }
    public int? b743 { get; set; }
    public int? b744 { get; set; }
    public int? b745 { get; set; }
    public int? b746 { get; set; }
    public int? b747 { get; set; }
    public int? b748 { get; set; }
    public int? b749 { get; set; }
    public int? b750 { get; set; }
    public int? b751 { get; set; }
    public int? b752 { get; set; }
    public int? b753 { get; set; }
    public int? b754 { get; set; }
    public int? b755 { get; set; }
    public int? b756 { get; set; }
    public int? b757 { get; set; }
    public int? b758 { get; set; }
    public int? b759 { get; set; }
    public int? b760 { get; set; }
    public int? b761 { get; set; }
    public int? b762 { get; set; }
    public int? b763 { get; set; }
    public int? b764 { get; set; }
    public int? b765 { get; set; }
    public int? b766 { get; set; }
    public int? b767 { get; set; }
    public int? b768 { get; set; }
    public int? b769 { get; set; }
    public int? b770 { get; set; }
    public int? b771 { get; set; }
    public int? b772 { get; set; }
    public int? b773 { get; set; }
    public int? b774 { get; set; }
    public int? b775 { get; set; }
    public int? b776 { get; set; }
    public int? b777 { get; set; }
    public int? b778 { get; set; }
    public int? b779 { get; set; }
    public int? b780 { get; set; }
    public int? b781 { get; set; }
    public int? b782 { get; set; }
    public int? b783 { get; set; }
    public int? b784 { get; set; }
    public int? b785 { get; set; }
    public int? b786 { get; set; }
    public int? b787 { get; set; }
    public int? b788 { get; set; }
    public int? b789 { get; set; }
    public int? b790 { get; set; }
    public int? b791 { get; set; }
    public int? b792 { get; set; }
    public int? b793 { get; set; }
    public int? b794 { get; set; }
    public int? b795 { get; set; }
    public int? b796 { get; set; }
    public int? b797 { get; set; }
    public int? b798 { get; set; }
    public int? b799 { get; set; }
    public int? b800 { get; set; }
    public int? b801 { get; set; }
    public int? b802 { get; set; }
    public int? b803 { get; set; }
    public int? b804 { get; set; }
    public int? b805 { get; set; }
    public int? b806 { get; set; }
    public int? b807 { get; set; }
    public int? b808 { get; set; }
    public int? b809 { get; set; }
    public int? b810 { get; set; }
    public int? b811 { get; set; }
    public int? b812 { get; set; }
    public int? b813 { get; set; }
    public int? b814 { get; set; }
    public int? b815 { get; set; }
    public int? b816 { get; set; }
    public int? b817 { get; set; }
    public int? b818 { get; set; }
    public int? b819 { get; set; }
    public int? b820 { get; set; }
    public int? b821 { get; set; }
    public int? b822 { get; set; }
    public int? b823 { get; set; }
    public int? b824 { get; set; }
    public int? b825 { get; set; }
    public int? b826 { get; set; }
    public int? b827 { get; set; }
    public int? b828 { get; set; }
    public int? b829 { get; set; }
    public int? b830 { get; set; }
    public int? b831 { get; set; }
    public int? b832 { get; set; }
    public int? b833 { get; set; }
    public int? b834 { get; set; }
    public int? b835 { get; set; }
    public int? b836 { get; set; }
    public int? b837 { get; set; }
    public int? b838 { get; set; }
    public int? b839 { get; set; }
    public int? b840 { get; set; }
    public int? b841 { get; set; }
    public int? b842 { get; set; }
    public int? b843 { get; set; }
    public int? b844 { get; set; }
    public int? b845 { get; set; }
    public int? b846 { get; set; }
    public int? b847 { get; set; }
    public int? b848 { get; set; }
    public int? b849 { get; set; }
    public int? b850 { get; set; }
    public int? b851 { get; set; }
    public int? b852 { get; set; }
    public int? b853 { get; set; }
    public int? b854 { get; set; }
    public int? b855 { get; set; }
    public int? b856 { get; set; }
    public int? b857 { get; set; }
    public int? b858 { get; set; }
    public int? b859 { get; set; }
    public int? b860 { get; set; }
    public int? b861 { get; set; }
    public int? b862 { get; set; }
    public int? b863 { get; set; }
    public int? b864 { get; set; }
    public int? b865 { get; set; }
    public int? b866 { get; set; }
    public int? b867 { get; set; }
    public int? b868 { get; set; }
    public int? b869 { get; set; }
    public int? b870 { get; set; }
    public int? b871 { get; set; }
    public int? b872 { get; set; }
    public int? b873 { get; set; }
    public int? b874 { get; set; }
    public int? b875 { get; set; }
    public int? b876 { get; set; }
    public int? b877 { get; set; }
    public int? b878 { get; set; }
    public int? b879 { get; set; }
    public int? b880 { get; set; }
    public int? b881 { get; set; }
    public int? b882 { get; set; }
    public int? b883 { get; set; }
    public int? b884 { get; set; }
    public int? b885 { get; set; }
    public int? b886 { get; set; }
    public int? b887 { get; set; }
    public int? haha { get; set; }
    public int? b888 { get; set; }
    public int? b889 { get; set; }
    public int? b890 { get; set; }
    public int? b891 { get; set; }
    public int? b892 { get; set; }
    public int? b893 { get; set; }
    public int? b894 { get; set; }
    public int? b895 { get; set; }
    public int? b896 { get; set; }
    public int? b897 { get; set; }
    public int? b898 { get; set; }
    public int? b899 { get; set; }
    public int? b900 { get; set; }
    public int? b901 { get; set; }
    public int? b902 { get; set; }
    public int? b903 { get; set; }
    public int? b904 { get; set; }
    public int? b905 { get; set; }
    public int? b906 { get; set; }
    public int? b907 { get; set; }
    public int? b908 { get; set; }
    public int? b909 { get; set; }
    public int? b910 { get; set; }
    public int? b911 { get; set; }
    public int? b912 { get; set; }
    public int? b913 { get; set; }
    public int? b914 { get; set; }
    public int? b915 { get; set; }
    public int? b916 { get; set; }
    public int? b917 { get; set; }
    public int? b918 { get; set; }
    public int? b919 { get; set; }
    public int? b920 { get; set; }
    public int? b921 { get; set; }
    public int? b922 { get; set; }
    public int? b923 { get; set; }
    public int? b924 { get; set; }
    public int? b925 { get; set; }
    public int? b926 { get; set; }
    public int? b927 { get; set; }
    public int? b928 { get; set; }
    public int? b929 { get; set; }
    public int? b930 { get; set; }
    public int? b931 { get; set; }
    public int? b932 { get; set; }
    public int? b933 { get; set; }
    public int? b934 { get; set; }
    public int? b935 { get; set; }
    public int? b936 { get; set; }
    public int? b937 { get; set; }
    public int? b938 { get; set; }
    public int? b939 { get; set; }
    public int? b940 { get; set; }
    public int? b941 { get; set; }
    public int? b942 { get; set; }
    public int? b943 { get; set; }
    public int? b944 { get; set; }
    public int? b945 { get; set; }
    public int? b946 { get; set; }
    public int? b947 { get; set; }
    public int? b948 { get; set; }
    public int? b949 { get; set; }
    public int? b950 { get; set; }
    public int? b951 { get; set; }
    public int? b952 { get; set; }
    public int? b953 { get; set; }
    public int? b954 { get; set; }
    public int? b955 { get; set; }
    public int? b956 { get; set; }
    public int? b957 { get; set; }
    public int? b958 { get; set; }
    public int? b959 { get; set; }
    public int? b960 { get; set; }
    public int? b961 { get; set; }
    public int? b962 { get; set; }
    public int? b963 { get; set; }
    public int? b964 { get; set; }
    public int? b965 { get; set; }
    public int? b966 { get; set; }
    public int? b967 { get; set; }
    public int? b968 { get; set; }
    public int? b969 { get; set; }
    public int? b970 { get; set; }
    public int? b971 { get; set; }
    public int? b972 { get; set; }
    public int? b973 { get; set; }
    public int? b974 { get; set; }
    public int? b975 { get; set; }
    public int? b976 { get; set; }
    public int? b977 { get; set; }
    public int? b978 { get; set; }
    public int? b979 { get; set; }
    public int? b980 { get; set; }
    public int? b981 { get; set; }
    public int? b982 { get; set; }
    public int? b983 { get; set; }
    public int? b984 { get; set; }
    public int? b985 { get; set; }
    public int? b986 { get; set; }
    public int? b987 { get; set; }
    public int? b988 { get; set; }
    public int? b989 { get; set; }
    public int? b990 { get; set; }
    public int? b991 { get; set; }
    public int? b992 { get; set; }
    public int? b993 { get; set; }
    public int? b994 { get; set; }
    public int? b995 { get; set; }
    public int? b996 { get; set; }
    public int? b997 { get; set; }
    public int? b998 { get; set; }
    public int? b999 { get; set; }
    public int? b1000 { get; set; }
    public int? b1001 { get; set; }
    public int? b1002 { get; set; }
}
