using System;
public class d
{
    public int? d140 { get; set; }
    public int? d546 { get; set; }
    public int? d394 { get; set; }
    public int? d688 { get; set; }
    public int? d519 { get; set; }
    public int? d803 { get; set; }
    public int? d646 { get; set; }
    public int? d872 { get; set; }
    public int? d939 { get; set; }
    public int? d884 { get; set; }
    public int? d427 { get; set; }
    public int? d45 { get; set; }
    public int? d764 { get; set; }
    public int? d162 { get; set; }
    public int? d481 { get; set; }
    public int? d323 { get; set; }
    public int? d49 { get; set; }
    public int? d424 { get; set; }
    public int? d935 { get; set; }
    public int? d513 { get; set; }
    public int? d906 { get; set; }
    public int? d238 { get; set; }
    public int? d446 { get; set; }
    public int? d35 { get; set; }
    public int? d619 { get; set; }
    public int? d650 { get; set; }
    public int? d480 { get; set; }
    public int? d221 { get; set; }
    public int? d2 { get; set; }
    public int? d144 { get; set; }
    public int? d211 { get; set; }
    public int? d268 { get; set; }
    public int? d329 { get; set; }
    public int? d84 { get; set; }
    public int? d408 { get; set; }
    public int? d74 { get; set; }
    public int? d293 { get; set; }
    public int? d209 { get; set; }
    public int? d712 { get; set; }
    public int? d274 { get; set; }
    public int? d475 { get; set; }
    public int? d11 { get; set; }
    public int? d987 { get; set; }
    public int? d398 { get; set; }
    public int? d142 { get; set; }
    public int? d34 { get; set; }
    public int? d579 { get; set; }
    public int? d78 { get; set; }
    public int? d927 { get; set; }
    public int? d461 { get; set; }
    public int? d366 { get; set; }
    public int? d644 { get; set; }
    public int? d549 { get; set; }
    public int? d576 { get; set; }
    public int? d772 { get; set; }
    public int? d114 { get; set; }
    public int? d801 { get; set; }
    public int? d252 { get; set; }
    public int? d794 { get; set; }
    public int? d246 { get; set; }
    public int? d225 { get; set; }
    public int? d606 { get; set; }
    public int? d596 { get; set; }
    public int? d173 { get; set; }
    public int? d356 { get; set; }
    public int? d854 { get; set; }
    public int? d518 { get; set; }
    public int? d314 { get; set; }
    public int? d65 { get; set; }
    public int? d732 { get; set; }
    public int? d62 { get; set; }
    public int? d506 { get; set; }
    public int? d345 { get; set; }
    public int? d172 { get; set; }
    public int? d559 { get; set; }
    public int? d339 { get; set; }
    public int? d109 { get; set; }
    public int? d996 { get; set; }
    public int? d862 { get; set; }
    public int? d405 { get; set; }
    public int? d526 { get; set; }
    public int? d247 { get; set; }
    public int? d599 { get; set; }
    public int? d326 { get; set; }
    public int? d259 { get; set; }
    public int? d478 { get; set; }
    public int? d406 { get; set; }
    public int? d970 { get; set; }
    public int? d70 { get; set; }
    public int? d289 { get; set; }
    public int? d667 { get; set; }
    public int? d240 { get; set; }
    public int? d807 { get; set; }
    public int? d305 { get; set; }
    public int? d974 { get; set; }
    public int? d708 { get; set; }
    public int? d357 { get; set; }
    public int? d724 { get; set; }
    public int? d827 { get; set; }
    public int? d713 { get; set; }
    public int? d637 { get; set; }
    public int? d848 { get; set; }
    public int? d672 { get; set; }
    public int? d227 { get; set; }
    public int? d618 { get; set; }
    public int? d607 { get; set; }
    public int? d136 { get; set; }
    public int? d319 { get; set; }
    public int? d877 { get; set; }
    public int? d263 { get; set; }
    public int? d951 { get; set; }
    public int? d501 { get; set; }
    public int? d241 { get; set; }
    public int? d982 { get; set; }
    public int? d47 { get; set; }
    public int? d804 { get; set; }
    public int? d562 { get; set; }
    public int? d164 { get; set; }
    public int? d685 { get; set; }
    public int? d824 { get; set; }
    public int? d595 { get; set; }
    public int? d216 { get; set; }
    public int? d782 { get; set; }
    public int? d14 { get; set; }
    public int? d591 { get; set; }
    public int? d463 { get; set; }
    public int? d470 { get; set; }
    public int? d940 { get; set; }
    public int? d380 { get; set; }
    public int? d534 { get; set; }
    public int? d660 { get; set; }
    public int? d581 { get; set; }
    public int? d962 { get; set; }
    public int? d138 { get; set; }
    public int? d53 { get; set; }
    public int? d896 { get; set; }
    public int? d774 { get; set; }
    public int? d157 { get; set; }
    public int? d134 { get; set; }
    public int? d736 { get; set; }
    public int? d254 { get; set; }
    public int? d578 { get; set; }
    public int? d921 { get; set; }
    public int? d416 { get; set; }
    public int? d992 { get; set; }
    public int? d97 { get; set; }
    public int? d611 { get; set; }
    public int? d420 { get; set; }
    public int? d763 { get; set; }
    public int? d119 { get; set; }
    public int? d710 { get; set; }
    public int? d272 { get; set; }
    public int? d654 { get; set; }
    public int? d741 { get; set; }
    public int? d716 { get; set; }
    public int? d262 { get; set; }
    public int? d449 { get; set; }
    public int? d336 { get; set; }
    public int? d328 { get; set; }
    public int? d310 { get; set; }
    public int? d378 { get; set; }
    public int? d582 { get; set; }
    public int? d903 { get; set; }
    public int? d918 { get; set; }
    public int? d442 { get; set; }
    public int? d956 { get; set; }
    public int? d586 { get; set; }
    public int? d206 { get; set; }
    public int? d440 { get; set; }
    public int? d342 { get; set; }
    public int? d362 { get; set; }
    public int? d248 { get; set; }
    public int? d957 { get; set; }
    public int? d873 { get; set; }
    public int? d952 { get; set; }
    public int? d928 { get; set; }
    public int? d127 { get; set; }
    public int? d433 { get; set; }
    public int? d842 { get; set; }
    public int? d428 { get; set; }
    public int? d132 { get; set; }
    public int? d742 { get; set; }
    public int? d226 { get; set; }
    public int? d3 { get; set; }
    public int? d471 { get; set; }
    public int? d565 { get; set; }
    public int? d57 { get; set; }
    public int? d445 { get; set; }
    public int? d651 { get; set; }
    public int? d760 { get; set; }
    public int? d647 { get; set; }
    public int? d831 { get; set; }
    public int? d913 { get; set; }
    public int? d924 { get; set; }
    public int? d731 { get; set; }
    public int? d456 { get; set; }
    public int? d892 { get; set; }
    public int? d368 { get; set; }
    public int? d55 { get; set; }
    public int? d284 { get; set; }
    public int? d496 { get; set; }
    public int? d51 { get; set; }
    public int? d291 { get; set; }
    public int? d699 { get; set; }
    public int? d938 { get; set; }
    public int? d798 { get; set; }
    public int? d950 { get; set; }
    public int? d125 { get; set; }
    public int? d58 { get; set; }
    public int? d709 { get; set; }
    public int? d567 { get; set; }
    public int? d883 { get; set; }
    public int? d937 { get; set; }
    public int? d612 { get; set; }
    public int? d661 { get; set; }
    public int? d874 { get; set; }
    public int? d825 { get; set; }
    public int? d191 { get; set; }
    public int? d68 { get; set; }
    public int? d313 { get; set; }
    public int? d163 { get; set; }
    public int? d208 { get; set; }
    public int? d315 { get; set; }
    public int? d158 { get; set; }
    public int? d975 { get; set; }
    public int? d886 { get; set; }
    public int? d694 { get; set; }
    public int? d510 { get; set; }
    public int? d727 { get; set; }
    public int? d911 { get; set; }
    public int? d616 { get; set; }
    public int? d948 { get; set; }
    public int? d751 { get; set; }
    public int? d20 { get; set; }
    public int? d472 { get; set; }
    public int? d80 { get; set; }
    public int? d343 { get; set; }
    public int? d502 { get; set; }
    public int? d931 { get; set; }
    public int? d355 { get; set; }
    public int? d690 { get; set; }
    public int? d188 { get; set; }
    public int? d159 { get; set; }
    public int? d845 { get; set; }
    public int? d762 { get; set; }
    public int? d863 { get; set; }
    public int? d232 { get; set; }
    public int? d249 { get; set; }
    public int? d347 { get; set; }
    public int? d115 { get; set; }
    public int? d146 { get; set; }
    public int? d491 { get; set; }
    public int? d103 { get; set; }
    public int? d843 { get; set; }
    public int? d392 { get; set; }
    public int? d577 { get; set; }
    public int? d71 { get; set; }
    public int? d404 { get; set; }
    public int? d634 { get; set; }
    public int? d160 { get; set; }
    public int? d334 { get; set; }
    public int? d37 { get; set; }
    public int? d166 { get; set; }
    public int? d116 { get; set; }
    public int? d841 { get; set; }
    public int? d934 { get; set; }
    public int? d739 { get; set; }
    public int? d298 { get; set; }
    public int? d817 { get; set; }
    public int? d122 { get; set; }
    public int? d682 { get; set; }
    public int? d942 { get; set; }
    public int? d972 { get; set; }
    public int? d900 { get; set; }
    public int? d847 { get; set; }
    public int? d161 { get; set; }
    public int? d275 { get; set; }
    public int? d474 { get; set; }
    public int? d735 { get; set; }
    public int? d407 { get; set; }
    public int? d860 { get; set; }
    public int? d759 { get; set; }
    public int? d790 { get; set; }
    public int? d231 { get; set; }
    public int? d524 { get; set; }
    public int? d973 { get; set; }
    public int? d40 { get; set; }
    public int? d770 { get; set; }
    public int? d308 { get; set; }
    public int? d242 { get; set; }
    public int? d373 { get; set; }
    public int? d720 { get; set; }
    public int? d66 { get; set; }
    public int? d568 { get; set; }
    public int? d693 { get; set; }
    public int? d67 { get; set; }
    public int? d932 { get; set; }
    public int? d415 { get; set; }
    public int? d151 { get; set; }
    public int? d69 { get; set; }
    public int? d737 { get; set; }
    public int? d556 { get; set; }
    public int? d383 { get; set; }
    public int? d965 { get; set; }
    public int? d614 { get; set; }
    public int? d733 { get; set; }
    public int? d929 { get; set; }
    public int? d182 { get; set; }
    public int? d740 { get; set; }
    public int? d410 { get; set; }
    public int? d112 { get; set; }
    public int? d145 { get; set; }
    public int? d728 { get; set; }
    public int? d23 { get; set; }
    public int? d439 { get; set; }
    public int? d552 { get; set; }
    public int? d27 { get; set; }
    public int? d547 { get; set; }
    public int? d668 { get; set; }
    public int? d452 { get; set; }
    public int? d700 { get; set; }
    public int? d360 { get; set; }
    public int? d210 { get; set; }
    public int? d256 { get; set; }
    public int? d261 { get; set; }
    public int? d636 { get; set; }
    public int? d561 { get; set; }
    public int? d600 { get; set; }
    public int? d184 { get; set; }
    public int? d985 { get; set; }
    public int? d508 { get; set; }
    public int? d237 { get; set; }
    public int? d976 { get; set; }
    public int? d391 { get; set; }
    public int? d222 { get; set; }
    public int? d150 { get; set; }
    public int? d412 { get; set; }
    public int? d697 { get; set; }
    public int? d22 { get; set; }
    public int? d29 { get; set; }
    public int? d784 { get; set; }
    public int? d749 { get; set; }
    public int? d604 { get; set; }
    public int? d13 { get; set; }
    public int? d152 { get; set; }
    public int? d402 { get; set; }
    public int? d56 { get; set; }
    public int? d516 { get; set; }
    public int? d503 { get; set; }
    public int? d642 { get; set; }
    public int? d641 { get; set; }
    public int? d396 { get; set; }
    public int? d621 { get; set; }
    public int? d317 { get; set; }
    public int? d204 { get; set; }
    public int? d411 { get; set; }
    public int? d815 { get; set; }
    public int? d553 { get; set; }
    public int? d213 { get; set; }
    public int? d290 { get; set; }
    public int? d941 { get; set; }
    public int? d775 { get; set; }
    public int? d95 { get; set; }
    public int? d458 { get; set; }
    public int? d266 { get; set; }
    public int? d426 { get; set; }
    public int? d855 { get; set; }
    public int? d983 { get; set; }
    public int? d167 { get; set; }
    public int? d64 { get; set; }
    public int? d584 { get; set; }
    public int? d189 { get; set; }
    public int? d572 { get; set; }
    public int? d811 { get; set; }
    public int? d369 { get; set; }
    public int? d462 { get; set; }
    public int? d730 { get; set; }
    public int? d666 { get; set; }
    public int? d514 { get; set; }
    public int? d967 { get; set; }
    public int? d812 { get; set; }
    public int? d923 { get; set; }
    public int? d175 { get; set; }
    public int? d333 { get; set; }
    public int? d914 { get; set; }
    public int? d638 { get; set; }
    public int? d945 { get; set; }
    public int? d244 { get; set; }
    public int? d46 { get; set; }
    public int? d560 { get; set; }
    public int? d73 { get; set; }
    public int? d813 { get; set; }
    public int? d224 { get; set; }
    public int? d277 { get; set; }
    public int? d671 { get; set; }
    public int? d986 { get; set; }
    public int? d533 { get; set; }
    public int? d678 { get; set; }
    public int? d570 { get; set; }
    public int? d105 { get; set; }
    public int? d387 { get; set; }
    public int? d613 { get; set; }
    public int? d464 { get; set; }
    public int? d944 { get; set; }
    public int? d234 { get; set; }
    public int? d75 { get; set; }
    public int? d623 { get; set; }
    public int? d746 { get; set; }
    public int? d361 { get; set; }
    public int? d425 { get; set; }
    public int? d434 { get; set; }
    public int? d25 { get; set; }
    public int? d100 { get; set; }
    public int? d991 { get; set; }
    public int? d245 { get; set; }
    public int? d754 { get; set; }
    public int? d981 { get; set; }
    public int? d459 { get; set; }
    public int? d648 { get; set; }
    public int? d545 { get; set; }
    public int? d836 { get; set; }
    public int? d457 { get; set; }
    public int? d294 { get; set; }
    public int? d76 { get; set; }
    public int? d675 { get; set; }
    public int? d374 { get; set; }
    public int? d695 { get; set; }
    public int? d756 { get; set; }
    public int? d925 { get; set; }
    public int? d4 { get; set; }
    public int? d468 { get; set; }
    public int? d605 { get; set; }
    public int? d840 { get; set; }
    public int? d890 { get; set; }
    public int? d969 { get; set; }
    public int? d652 { get; set; }
    public int? d466 { get; set; }
    public int? d98 { get; set; }
    public int? d990 { get; set; }
    public int? d228 { get; set; }
    public int? d835 { get; set; }
    public int? d435 { get; set; }
    public int? d498 { get; set; }
    public int? d260 { get; set; }
    public int? d766 { get; set; }
    public int? d588 { get; set; }
    public int? d423 { get; set; }
    public int? d335 { get; set; }
    public int? d617 { get; set; }
    public int? d473 { get; set; }
    public int? d88 { get; set; }
    public int? d190 { get; set; }
    public int? d626 { get; set; }
    public int? d997 { get; set; }
    public int? d118 { get; set; }
    public int? d265 { get; set; }
    public int? d833 { get; set; }
    public int? d718 { get; set; }
    public int? d657 { get; set; }
    public int? d866 { get; set; }
    public int? d633 { get; set; }
    public int? d748 { get; set; }
    public int? d777 { get; set; }
    public int? d82 { get; set; }
    public int? d705 { get; set; }
    public int? d711 { get; set; }
    public int? d124 { get; set; }
    public int? d800 { get; set; }
    public int? d532 { get; set; }
    public int? d269 { get; set; }
    public int? d181 { get; set; }
    public int? d989 { get; set; }
    public int? d155 { get; set; }
    public int? d856 { get; set; }
    public int? d330 { get; set; }
    public int? d920 { get; set; }
    public int? d302 { get; set; }
    public int? d129 { get; set; }
    public int? d490 { get; set; }
    public int? d94 { get; set; }
    public int? d363 { get; set; }
    public int? d590 { get; set; }
    public int? d995 { get; set; }
    public int? d243 { get; set; }
    public int? d878 { get; set; }
    public int? d102 { get; set; }
    public int? d630 { get; set; }
    public int? d702 { get; set; }
    public int? d33 { get; set; }
    public int? d385 { get; set; }
    public int? d399 { get; set; }
    public int? d235 { get; set; }
    public int? d1001 { get; set; }
    public int? d946 { get; set; }
    public int? d303 { get; set; }
    public int? d436 { get; set; }
    public int? d101 { get; set; }
    public int? d505 { get; set; }
    public int? d376 { get; set; }
    public int? d174 { get; set; }
    public int? d5 { get; set; }
    public int? d31 { get; set; }
    public int? d280 { get; set; }
    public int? d851 { get; set; }
    public int? d658 { get; set; }
    public int? d719 { get; set; }
    public int? d738 { get; set; }
    public int? d499 { get; set; }
    public int? d230 { get; set; }
    public int? d93 { get; set; }
    public int? d87 { get; set; }
    public int? d196 { get; set; }
    public int? d212 { get; set; }
    public int? d137 { get; set; }
    public int? d839 { get; set; }
    public int? d201 { get; set; }
    public int? d953 { get; set; }
    public int? d388 { get; set; }
    public int? d15 { get; set; }
    public int? d72 { get; set; }
    public int? d639 { get; set; }
    public int? d954 { get; set; }
    public int? d397 { get; set; }
    public int? d870 { get; set; }
    public int? d495 { get; set; }
    public int? d107 { get; set; }
    public int? d994 { get; set; }
    public int? d721 { get; set; }
    public int? d465 { get; set; }
    public int? d979 { get; set; }
    public int? d810 { get; set; }
    public int? d655 { get; set; }
    public int? d251 { get; set; }
    public int? d359 { get; set; }
    public int? d348 { get; set; }
    public int? d583 { get; set; }
    public int? d610 { get; set; }
    public int? d809 { get; set; }
    public int? d858 { get; set; }
    public int? d649 { get; set; }
    public int? d10 { get; set; }
    public int? d683 { get; set; }
    public int? d968 { get; set; }
    public int? d573 { get; set; }
    public int? d106 { get; set; }
    public int? d131 { get; set; }
    public int? d311 { get; set; }
    public int? d24 { get; set; }
    public int? d933 { get; set; }
    public int? d450 { get; set; }
    public int? d156 { get; set; }
    public int? d283 { get; set; }
    public int? d338 { get; set; }
    public int? d587 { get; set; }
    public int? d168 { get; set; }
    public int? d42 { get; set; }
    public int? d417 { get; set; }
    public int? d664 { get; set; }
    public int? d543 { get; set; }
    public int? d332 { get; set; }
    public int? d255 { get; set; }
    public int? d793 { get; set; }
    public int? d786 { get; set; }
    public int? d381 { get; set; }
    public int? d179 { get; set; }
    public int? d998 { get; set; }
    public int? d787 { get; set; }
    public int? d818 { get; set; }
    public int? d386 { get; set; }
    public int? d193 { get; set; }
    public int? d691 { get; set; }
    public int? d706 { get; set; }
    public int? d430 { get; set; }
    public int? d18 { get; set; }
    public int? d893 { get; set; }
    public int? d988 { get; set; }
    public int? d676 { get; set; }
    public int? d205 { get; set; }
    public int? d537 { get; set; }
    public int? d443 { get; set; }
    public int? d907 { get; set; }
    public int? d270 { get; set; }
    public int? d723 { get; set; }
    public int? d768 { get; set; }
    public int? d834 { get; set; }
    public int? d859 { get; set; }
    public int? d141 { get; set; }
    public int? d354 { get; set; }
    public int? d421 { get; set; }
    public int? d857 { get; set; }
    public int? d418 { get; set; }
    public int? d194 { get; set; }
    public int? d99 { get; set; }
    public int? d747 { get; set; }
    public int? d909 { get; set; }
    public int? d117 { get; set; }
    public int? d90 { get; set; }
    public int? d550 { get; set; }
    public int? d558 { get; set; }
    public int? d580 { get; set; }
    public int? d620 { get; set; }
    public int? d17 { get; set; }
    public int? d451 { get; set; }
    public int? d828 { get; set; }
    public int? d295 { get; set; }
    public int? d512 { get; set; }
    public int? d285 { get; set; }
    public int? d271 { get; set; }
    public int? d999 { get; set; }
    public int? d185 { get; set; }
    public int? d551 { get; set; }
    public int? d829 { get; set; }
    public int? d279 { get; set; }
    public int? d569 { get; set; }
    public int? d154 { get; set; }
    public int? d544 { get; set; }
    public int? d542 { get; set; }
    public int? d494 { get; set; }
    public int? d432 { get; set; }
    public int? d826 { get; set; }
    public int? d677 { get; set; }
    public int? d520 { get; set; }
    public int? d958 { get; set; }
    public int? d555 { get; set; }
    public int? d148 { get; set; }
    public int? d341 { get; set; }
    public int? d419 { get; set; }
    public int? d789 { get; set; }
    public int? d745 { get; set; }
    public int? d585 { get; set; }
    public int? d377 { get; set; }
    public int? d684 { get; set; }
    public int? d511 { get; set; }
    public int? d852 { get; set; }
    public int? d300 { get; set; }
    public int? d632 { get; set; }
    public int? d253 { get; set; }
    public int? d669 { get; set; }
    public int? d765 { get; set; }
    public int? d133 { get; set; }
    public int? d743 { get; set; }
    public int? d832 { get; set; }
    public int? d187 { get; set; }
    public int? d868 { get; set; }
    public int? d961 { get; set; }
    public int? d198 { get; set; }
    public int? d178 { get; set; }
    public int? d485 { get; set; }
    public int? d849 { get; set; }
    public int? d895 { get; set; }
    public int? d916 { get; set; }
    public int? d554 { get; set; }
    public int? d919 { get; set; }
    public int? d673 { get; set; }
    public int? d257 { get; set; }
    public int? d963 { get; set; }
    public int? d214 { get; set; }
    public int? d199 { get; set; }
    public int? d692 { get; set; }
    public int? d1002 { get; set; }
    public int? d63 { get; set; }
    public int? d44 { get; set; }
    public int? d486 { get; set; }
    public int? d96 { get; set; }
    public int? d54 { get; set; }
    public int? d92 { get; set; }
    public int? d59 { get; set; }
    public int? d108 { get; set; }
    public int? d635 { get; set; }
    public int? d273 { get; set; }
    public int? d875 { get; set; }
    public int? d307 { get; set; }
    public int? d528 { get; set; }
    public int? d197 { get; set; }
    public int? d81 { get; set; }
    public int? d541 { get; set; }
    public int? d850 { get; set; }
    public int? d715 { get; set; }
    public int? d629 { get; set; }
    public int? d32 { get; set; }
    public int? d717 { get; set; }
    public int? d401 { get; set; }
    public int? d880 { get; set; }
    public int? d504 { get; set; }
    public int? d714 { get; set; }
    public int? d409 { get; set; }
    public int? d171 { get; set; }
    public int? d947 { get; set; }
    public int? d203 { get; set; }
    public int? d659 { get; set; }
    public int? d820 { get; set; }
    public int? d755 { get; set; }
    public int? d698 { get; set; }
    public int? d370 { get; set; }
    public int? d984 { get; set; }
    public int? d609 { get; set; }
    public int? d758 { get; set; }
    public int? d679 { get; set; }
    public int? d902 { get; set; }
    public int? d111 { get; set; }
    public int? d321 { get; set; }
    public int? d891 { get; set; }
    public int? d943 { get; set; }
    public int? d805 { get; set; }
    public int? d278 { get; set; }
    public int? d43 { get; set; }
    public int? d631 { get; set; }
    public int? d864 { get; set; }
    public int? d531 { get; set; }
    public int? d282 { get; set; }
    public int? d331 { get; set; }
    public int? d538 { get; set; }
    public int? d753 { get; set; }
    public int? d640 { get; set; }
    public int? d48 { get; set; }
    public int? d624 { get; set; }
    public int? d515 { get; set; }
    public int? d808 { get; set; }
    public int? d429 { get; set; }
    public int? d522 { get; set; }
    public int? d799 { get; set; }
    public int? d153 { get; set; }
    public int? d912 { get; set; }
    public int? d250 { get; set; }
    public int? d525 { get; set; }
    public int? d971 { get; set; }
    public int? d548 { get; set; }
    public int? d170 { get; set; }
    public int? d881 { get; set; }
    public int? d453 { get; set; }
    public int? d358 { get; set; }
    public int? d500 { get; set; }
    public int? d822 { get; set; }
    public int? d28 { get; set; }
    public int? d36 { get; set; }
    public int? d846 { get; set; }
    public int? d509 { get; set; }
    public int? d926 { get; set; }
    public int? d371 { get; set; }
    public int? d444 { get; set; }
    public int? d788 { get; set; }
    public int? d476 { get; set; }
    public int? d955 { get; set; }
    public int? d722 { get; set; }
    public int? d400 { get; set; }
    public int? d521 { get; set; }
    public int? d615 { get; set; }
    public int? d908 { get; set; }
    public int? d949 { get; set; }
    public int? d149 { get; set; }
    public int? d838 { get; set; }
    public int? d529 { get; set; }
    public int? d783 { get; set; }
    public int? d853 { get; set; }
    public int? d922 { get; set; }
    public int? d574 { get; set; }
    public int? d816 { get; set; }
    public int? d287 { get; set; }
    public int? d441 { get; set; }
    public int? d564 { get; set; }
    public int? d351 { get; set; }
    public int? d352 { get; set; }
    public int? d469 { get; set; }
    public int? d316 { get; set; }
    public int? d781 { get; set; }
    public int? d681 { get; set; }
    public int? d704 { get; set; }
    public int? d41 { get; set; }
    public int? d139 { get; set; }
    public int? d780 { get; set; }
    public int? d21 { get; set; }
    public int? d665 { get; set; }
    public int? d297 { get; set; }
    public int? d288 { get; set; }
    public int? d484 { get; set; }
    public int? d602 { get; set; }
    public int? d220 { get; set; }
    public int? d539 { get; set; }
    public int? d773 { get; set; }
    public int? d229 { get; set; }
    public int? d306 { get; set; }
    public int? d202 { get; set; }
    public int? d489 { get; set; }
    public int? d535 { get; set; }
    public int? d734 { get; set; }
    public int? d966 { get; set; }
    public int? d729 { get; set; }
    public int? d60 { get; set; }
    public int? d372 { get; set; }
    public int? d867 { get; set; }
    public int? d389 { get; set; }
    public int? d837 { get; set; }
    public int? d597 { get; set; }
    public int? d30 { get; set; }
    public int? d622 { get; set; }
    public int? d865 { get; set; }
    public int? d382 { get; set; }
    public int? d977 { get; set; }
    public int? d575 { get; set; }
    public int? d413 { get; set; }
    public int? d123 { get; set; }
    public int? d1000 { get; set; }
    public int? d662 { get; set; }
    public int? d628 { get; set; }
    public int? d414 { get; set; }
    public int? d349 { get; set; }
    public int? d258 { get; set; }
    public int? d936 { get; set; }
    public int? d126 { get; set; }
    public int? d802 { get; set; }
    public int? d776 { get; set; }
    public int? d83 { get; set; }
    public int? d431 { get; set; }
    public int? d301 { get; set; }
    public int? d165 { get; set; }
    public int? d422 { get; set; }
    public int? d110 { get; set; }
    public int? d830 { get; set; }
    public int? d340 { get; set; }
    public int? d322 { get; set; }
    public int? d200 { get; set; }
    public int? d757 { get; set; }
    public int? d725 { get; set; }
    public int? d601 { get; set; }
    public int? d785 { get; set; }
    public int? d769 { get; set; }
    public int? d467 { get; set; }
    public int? d50 { get; set; }
    public int? d885 { get; set; }
    public int? d86 { get; set; }
    public int? d993 { get; set; }
    public int? d898 { get; set; }
    public int? d978 { get; set; }
    public int? d889 { get; set; }
    public int? d915 { get; set; }
    public int? d6 { get; set; }
    public int? d492 { get; set; }
    public int? d627 { get; set; }
    public int? d477 { get; set; }
    public int? d324 { get; set; }
    public int? d390 { get; set; }
    public int? d530 { get; set; }
    public int? d598 { get; set; }
    public int? d527 { get; set; }
    public int? d39 { get; set; }
    public int? d696 { get; set; }
    public int? d523 { get; set; }
    public int? d353 { get; set; }
    public int? d589 { get; set; }
    public int? d653 { get; set; }
    public int? d960 { get; set; }
    public int? d223 { get; set; }
    public int? d663 { get; set; }
    public int? d192 { get; set; }
    public int? d792 { get; set; }
    public int? d882 { get; set; }
    public int? d85 { get; set; }
    public int? d180 { get; set; }
    public int? d879 { get; set; }
    public int? d806 { get; set; }
    public int? d403 { get; set; }
    public int? d899 { get; set; }
    public int? d218 { get; set; }
    public int? d350 { get; set; }
    public int? d778 { get; set; }
    public int? d566 { get; set; }
    public int? d7 { get; set; }
    public int? d77 { get; set; }
    public int? d507 { get; set; }
    public int? d375 { get; set; }
    public int? d104 { get; set; }
    public int? d645 { get; set; }
    public int? d19 { get; set; }
    public int? d135 { get; set; }
    public int? d814 { get; set; }
    public int? d346 { get; set; }
    public int? d917 { get; set; }
    public int? d379 { get; set; }
    public int? d233 { get; set; }
    public int? d236 { get; set; }
    public int? d276 { get; set; }
    public int? d344 { get; set; }
    public int? d905 { get; set; }
    public int? d143 { get; set; }
    public int? d563 { get; set; }
    public int? d128 { get; set; }
    public int? d744 { get; set; }
    public int? d120 { get; set; }
    public int? d901 { get; set; }
    public int? d79 { get; set; }
    public int? d791 { get; set; }
    public int? d195 { get; set; }
    public int? d703 { get; set; }
    public int? d239 { get; set; }
    public int? d367 { get; set; }
    public int? d726 { get; set; }
    public int? d38 { get; set; }
    public int? d8 { get; set; }
    public int? d9 { get; set; }
}
